/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import file.PaquetesTuristicosFile;
import javax.swing.DefaultListModel;
import model.Localizacion;

/**
 *
 * @author Mele13
 */
public class PaqueteTuristico extends javax.swing.JFrame {

    public PaqueteTuristico paqTur;
    private String[] paquetes;
    public PaquetesTuristicosFile file;

    /**
     * Creates new form PaqueteTuristico
     */
    private String[] listarPaquetesPorLocalizacion(Localizacion localizacion) {

        String[] paquetes = (String[]) file.cargarPaquetesTuristicos(localizacion).toArray();

        DefaultListModel lm = new DefaultListModel();
        for (int i = 0; i < paquetes.length; i++) {
            lm.add(i, paquetes[i]);
        }
        return paquetes;
    }

    public PaqueteTuristico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        busquedaPaqTur_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPaquetes = new javax.swing.JList<>();
        localizacion_ComboBox = new javax.swing.JComboBox<>();
        seleccionar_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        busquedaPaqTur_Button.setText("Buscar por paquetes turísticos");

        listaPaquetes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = paquetes;
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaPaquetes);

        localizacion_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gran Canaria", "Fuerteventura", "Lanzarote", "La Graciosa", "Tenerife", "La Gomera", "La Palma", "El Hierro"}));
        localizacion_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizacion_ComboBoxActionPerformed(evt);
            }
        });

        seleccionar_Button.setText("Seleccionar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(busquedaPaqTur_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(localizacion_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seleccionar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(busquedaPaqTur_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(localizacion_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seleccionar_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void localizacion_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizacion_ComboBoxActionPerformed
        // TODO add your handling code here:       
        switch (localizacion_ComboBox.getSelectedIndex()) {
            case 1:
                listarPaquetesPorLocalizacion(Localizacion.GRANCANARIA);
            case 2:
                listarPaquetesPorLocalizacion(Localizacion.FUERTEVENTURA);
            case 3:
                listarPaquetesPorLocalizacion(Localizacion.LANZAROTE);
            case 4:
                listarPaquetesPorLocalizacion(Localizacion.GRACIOSA);
            case 5:
                listarPaquetesPorLocalizacion(Localizacion.TENERIFE);
            case 6:
                listarPaquetesPorLocalizacion(Localizacion.GOMERA);
            case 7:
                listarPaquetesPorLocalizacion(Localizacion.PALMA);
            case 8:
                listarPaquetesPorLocalizacion(Localizacion.HIERRO);
        }
    }//GEN-LAST:event_localizacion_ComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton busquedaPaqTur_Button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaPaquetes;
    private javax.swing.JComboBox<String> localizacion_ComboBox;
    private javax.swing.JButton seleccionar_Button;
    // End of variables declaration//GEN-END:variables
}
